### ISSUE TITLE
ETAPA 2

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#1]

**Comment by WalisonDaniel** [comment]
*Definição do Problema e Ideia de Solução:*
O problema central é a crescente disseminação de fake news envolvendo deep fakes, que afeta diretamente idosos, um público que muitas vezes não possui o conhecimento técnico necessário para identificar conteúdos falsificados. A solução proposta busca educar e capacitar os idosos para reconhecer deep fakes, ajudando a minimizar os impactos das fake news e protegê-los de fraudes e desinformações.

### *Personas*

#### 1. João Santos
- *Idade*: 67 anos
- *Naturalidade*: Belo Horizonte, Minas Gerais
- *Ocupação*: Aposentado, ex-contador
- *Atribuições*: Gerencia as finanças da casa e organiza a vida familiar.
- *Motivações*: João deseja se manter atualizado com notícias e eventos globais e tem interesse em proteger sua família contra golpes digitais.
- *Frustrações*: Enfrenta dificuldades para distinguir entre notícias verdadeiras e falsas em redes sociais e grupos de mensagens, especialmente quando envolvem vídeos aparentemente reais. Ele já foi vítima de boatos que geraram preocupações desnecessárias.
- *Hobbies, história*: Gosta de assistir futebol e acompanhar a política, mas se sente desatualizado em relação às novas tecnologias.

*Histórias de Usuário - João Santos*:
1. Como idoso ativo online, João quer entender como identificar vídeos deep fake para não espalhar informações enganosas entre seus amigos e familiares.
2. Como responsável pelas finanças, João quer saber como evitar golpes financeiros que usam vídeos falsos para parecerem legítimos.
3. Como consumidor de notícias, João deseja aprender a verificar a autenticidade de vídeos virais antes de confiar em suas mensagens.

#### 2. Maria Aparecida
- *Idade*: 72 anos
- *Naturalidade*: Contagem, Minas Gerais
- *Ocupação*: Dona de casa aposentada
- *Atribuições*: Cuida da casa e interage com amigos e parentes por meio de redes sociais.
- *Motivações*: Maria quer continuar conectada com sua família e amigos online, especialmente seus netos, e tem interesse em aprender a usar a internet de forma mais segura.
- *Frustrações*: Ela tem dificuldade em entender novas tecnologias e já foi confundida por vídeos falsos enviados em grupos de mensagens, o que gerou discussões familiares.
- *Hobbies, história*: Gosta de jardinagem e de conversar com seus vizinhos, mas se sente insegura quanto ao uso das redes sociais e novas formas de comunicação digital.

*Histórias de Usuário - Maria Aparecida*:
1. Como usuária de redes sociais, Maria quer saber como distinguir vídeos deep fake para não ser enganada ao compartilhar conteúdo com seus amigos.
2. Como avó conectada, Maria deseja aprender a verificar a autenticidade de vídeos antes de repassar para seus netos, garantindo que eles recebam apenas informações corretas.
3. Como membro ativo de grupos online, Maria quer participar de conversas com confiança, sabendo que está compartilhando informações verdadeiras e relevantes.

### *Requisitos Funcionais*:
1. O sistema deve disponibilizar vídeos e artigos educativos acessíveis que ensinem a identificar sinais de deep fakes.
2. O sistema deve incluir ferramentas de verificação simples para ajudar os idosos a testar a autenticidade de vídeos e áudios.
3. O sistema deve permitir que os usuários denunciem conteúdo suspeito de ser fake news para revisão.

### *Requisitos Não Funcionais*:
1. O sistema deve ser fácil de usar, com uma interface intuitiva adaptada ao público idoso.
2. O conteúdo educativo deve ser apresentado em linguagem clara e acessível, evitando termos técnicos complicados.
3. O sistema deve garantir segurança e privacidade aos usuários, protegendo suas informações pessoais e dados de navegação.

### *Artefatos Produzidos para Levantamento de Dados*:
1. Entrevistas com idosos para entender suas principais dúvidas e dificuldades ao interagir com conteúdos online.
2. Pesquisa com especialistas em deep fakes para definir os principais sinais de falsificações que serão abordados.
3. Prototipagem de interfaces e testes de usabilidade com o público-alvo para garantir que o sistema atenda às necessidades dos usuários finais.

Essa abordagem centrada no usuário garantirá que a solução seja eficaz e acessível para o público idoso.

Histórias de Usuário Relevantes para o Projeto
Persona 1: João Santos
Eu, como João Santos, quero aprender a identificar deep fakes para evitar compartilhar fake news com meus amigos e familiares.

Eu, como João Santos, preciso de uma ferramenta simples para verificar a autenticidade de vídeos para garantir que as notícias que compartilho sejam verdadeiras.

Eu, como João Santos, quero entender os riscos associados a vídeos deep fakes usados em golpes financeiros para proteger meu patrimônio e evitar fraudes.

Persona 2: Maria Aparecida
Eu, como Maria Aparecida, quero aprender a identificar vídeos e áudios deep fakes para evitar ser enganada por notícias falsas enviadas nos grupos de mensagens.

Eu, como Maria Aparecida, preciso de orientações claras e fáceis de entender para distinguir entre vídeos verdadeiros e falsos nas redes sociais.

Eu, como Maria Aparecida, quero poder compartilhar conteúdos com segurança para não disseminar informações falsas para meus familiares, especialmente meus netos.

Contexto Agrupado por Funcionalidade
Educação sobre Deep Fakes
João Santos: Precisa aprender a identificar deep fakes para não compartilhar notícias falsas.
Maria Aparecida: Quer aprender a identificar deep fakes em vídeos e áudios.
Ferramentas de Verificação
João Santos: Quer uma ferramenta para verificar a autenticidade de vídeos.
Maria Aparecida: Precisa de instruções simples e claras para distinguir vídeos reais dos falsos.
Proteção contra Golpes
João Santos: Deseja entender os riscos financeiros associados a deep fakes.
Maria Aparecida: Quer garantir que o conteúdo que compartilha com a família seja seguro e verdadeiro.
Essas histórias de usuários guiam o desenvolvimento das funcionalidades e ajudam a identificar como a prática extensionista pode minimizar as dores e aumentar a segurança digital dos idosos.

### *Requisitos Funcionais (RF)*

| *ID*    | *Descrição do Requisito*                                                                 | *Prioridade* |
|-----------|---------------------------------------------------------------------------------------------|----------------|
| RF-001    | O sistema deve fornecer vídeos e artigos educativos sobre deep fakes, com explicações claras e exemplos. | ALTA           |
| RF-002    | O sistema deve incluir uma ferramenta simples para verificar a autenticidade de vídeos deep fake.       | ALTA           |
| RF-003    | O sistema deve permitir que os usuários denunciem vídeos suspeitos de serem deep fakes.                 | MÉDIA          |
| RF-004    | O sistema deve oferecer orientações práticas para reconhecer sinais de manipulação em vídeos e áudios. | ALTA           |
| RF-005    | O sistema deve fornecer um mecanismo de feedback para que os usuários relatem sua experiência ao utilizar as ferramentas. | MÉDIA          |

### *Requisitos Não Funcionais (RNF)*

| *ID*    | *Descrição do Requisito*                                                      | *Prioridade* |
|-----------|---------------------------------------------------------------------------------|----------------|
| RNF-001   | O sistema deve ser intuitivo, com uma interface de fácil uso para idosos.        | ALTA           |
| RNF-002   | O sistema deve ser compatível com dispositivos móveis e navegadores de desktop.  | ALTA           |
| RNF-003   | O tempo de resposta da ferramenta de verificação deve ser inferior a 3 segundos. | MÉDIA          |
| RNF-004   | O conteúdo deve ser apresentado em linguagem acessível, evitando termos técnicos complicados. | ALTA           |
| RNF-005   | O sistema deve garantir a privacidade dos usuários, protegendo seus dados pessoais. | ALTA           |

Esses requisitos garantem que o sistema será acessível, funcional, e atenderá às necessidades do público-alvo, além de garantir uma experiência de uso intuitiva e segura.**

### *Artefatos para Levantamento de Dados*

Para realizar o levantamento de dados e entrevistas com o público-alvo, o grupo utilizará os seguintes artefatos:

#### *1. Questionários de Percepção sobre Fake News e Deep Fakes*
- *Objetivo*: Avaliar o conhecimento prévio dos idosos sobre fake news e deep fakes, além de identificar as principais dificuldades que eles enfrentam ao usar a internet e redes sociais.
- *Formato*: Questionário de múltipla escolha e perguntas abertas.
- *Estratégia de Aplicação*: 
  - Aplicação *in loco* em centros comunitários e grupos de convivência para idosos.
  - Também será disponibilizado *via web* em grupos de redes sociais voltados para idosos, facilitando o acesso ao questionário.
- *Divulgação*: Será feito através de cartazes nas instituições de convivência de idosos, além de postagens em grupos de WhatsApp e Facebook, com o apoio de membros dessas comunidades.

#### *2. Entrevistas Semiestruturadas*
- *Objetivo*: Coletar informações detalhadas sobre as percepções dos idosos em relação ao conteúdo digital e como eles verificam a autenticidade de informações, além de suas experiências anteriores com fake news.
- *Estratégia de Aplicação*:
  - Realizadas *presencialmente* com participantes que se mostrem dispostos após o preenchimento do questionário.
  - As entrevistas serão gravadas (com consentimento) para análise posterior.

#### *3. Prototipagem de Interface*
- *Objetivo*: Testar a usabilidade da interface proposta para o sistema de verificação de deep fakes.
- *Estratégia de Aplicação*:
  - Realizar sessões de testes com um grupo de idosos, em que eles interajam com protótipos navegáveis da interface.
  - *Feedback* será coletado por meio de observação e formulários, avaliando se as funcionalidades e a interface são intuitivas e fáceis de usar.

Esses artefatos permitirão uma análise aprofundada das necessidades do público-alvo, guiando o desenvolvimento da solução para que ela seja eficaz e acessível.

### *Referências*

1. *LOPEZ, M.* Deepfakes: Understanding the Impact on Misinformation and Privacy. Journal of Information Security, 2022.
2. *WANG, T., & GU, J.* Detecting Deepfake Media: A Survey. IEEE Transactions on Multimedia, 2021. 
3. *BBC News. *What are Deepfakes and How Can You Spot Them? Disponível em: [https://www.bbc.com/news/technology-50291077](https://www.bbc.com/news/technology-50291077). Acesso em: 01 set. 2024.
4. *SOUSA, P. R., & SILVA, M. B. *Fake News e a Terceira Idade: Desafios na Era Digital. Revista de Comunicação e Sociedade, 2023.
5. *LUCA, D., & MARTINS, L.* Como a Tecnologia de Deepfakes Está Impactando a Sociedade: Uma Análise de Casos Recentes. Revista Brasileira de Ciências da Informação, 2023.
6. *The Guardian. *Deepfakes: How Are They Made and How to Spot Them? Disponível em: [https://www.theguardian.com/technology/deepfakes](https://www.theguardian.com/technology/deepfakes). Acesso em: 30 ago. 2024.
7. *VIEIRA, A. S., & COSTA, P. R. *Educação Digital para Idosos: O Papel da Tecnologia no Combate às Fake News. Proceedings of the Digital Inclusion Conference, 2022.
