### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#10]

**Comment by samukjacinto** [comment]
Claro, aqui está uma descrição de uma persona idosa:

**Nome:** Dona Maria

**Idade:** 78 anos

**Profissão Anterior:** Professora de Literatura

**Contexto Familiar:** Viúva, mãe de dois filhos adultos e avó de quatro netos.

**Interesses e Hobbies:**
- Leitura de romances clássicos e poesias.
- Tricô e crochê, que usa para fazer presentes para a família.
- Participa de um grupo de jardinagem e gosta de cuidar das plantas do seu jardim.
- Assiste a filmes antigos e adora discutir sobre cinema com amigos.

**Personalidade:**
- Gentil e sábia, com um senso de humor afiado.
- Valoriza a tradição e a família, frequentemente organiza encontros familiares.
- Tem uma perspectiva positiva sobre a vida e gosta de compartilhar suas experiências e aprendizados.

**Desafios:**
- Mobilidade reduzida, usa um andador para se deslocar.
- Às vezes sente solidão, especialmente após a perda do esposo, mas se esforça para manter-se ativa e envolvida socialmente.

**Objetivos:**
- Manter-se saudável e independente o máximo possível.
- Transmitir suas memórias e conhecimentos para seus netos e outras gerações.
- Continuar aprendendo e se engajando em atividades que a façam feliz e realizada.

histórias de usuário 

- dona maria já sofreu com fakes news criadas por deep fake e compartilhou falsas histórias em grupos de whatsapp, causando brigas e confusões com amigos e familiares
- ⁠dona maria já quase caiu em golpes de cassinos online, ao ver um vídeo de um cantor famoso do qual ela admirava dizendo que o cassino estava pagando bem a todos os novos usuários, que depositassem uma certa quantia em dinheiro, e só não caiu pois pediu pra sua sobrinha lhe ajudar a fazer o depósito e a menina lhe aconselhou 
- ⁠dona maria já caiu em fake news sobre temas religiosos os quais lhe fizeram questionar sua fé e passar por momentos de crise
