### ISSUE TITLE
Histórias de Usuários

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#11]

**Comment by WalisonDaniel** [comment]
*Definição do Problema e Ideia de Solução:*
O problema central é a crescente disseminação de fake news envolvendo deep fakes, que afeta diretamente idosos, um público que muitas vezes não possui o conhecimento técnico necessário para identificar conteúdos falsificados. A solução proposta busca educar e capacitar os idosos para reconhecer deep fakes, ajudando a minimizar os impactos das fake news e protegê-los de fraudes e desinformações.

### *Personas*

#### 1. João Santos
- *Idade*: 67 anos
- *Naturalidade*: Belo Horizonte, Minas Gerais
- *Ocupação*: Aposentado, ex-contador
- *Atribuições*: Gerencia as finanças da casa e organiza a vida familiar.
- *Motivações*: João deseja se manter atualizado com notícias e eventos globais e tem interesse em proteger sua família contra golpes digitais.
- *Frustrações*: Enfrenta dificuldades para distinguir entre notícias verdadeiras e falsas em redes sociais e grupos de mensagens, especialmente quando envolvem vídeos aparentemente reais. Ele já foi vítima de boatos que geraram preocupações desnecessárias.
- *Hobbies, história*: Gosta de assistir futebol e acompanhar a política, mas se sente desatualizado em relação às novas tecnologias.

*Histórias de Usuário - João Santos*:
1. Como idoso ativo online, João quer entender como identificar vídeos deep fake para não espalhar informações enganosas entre seus amigos e familiares.
2. Como responsável pelas finanças, João quer saber como evitar golpes financeiros que usam vídeos falsos para parecerem legítimos.
3. Como consumidor de notícias, João deseja aprender a verificar a autenticidade de vídeos virais antes de confiar em suas mensagens.

#### 2. Maria Aparecida
- *Idade*: 72 anos
- *Naturalidade*: Contagem, Minas Gerais
- *Ocupação*: Dona de casa aposentada
- *Atribuições*: Cuida da casa e interage com amigos e parentes por meio de redes sociais.
- *Motivações*: Maria quer continuar conectada com sua família e amigos online, especialmente seus netos, e tem interesse em aprender a usar a internet de forma mais segura.
- *Frustrações*: Ela tem dificuldade em entender novas tecnologias e já foi confundida por vídeos falsos enviados em grupos de mensagens, o que gerou discussões familiares.
- *Hobbies, história*: Gosta de jardinagem e de conversar com seus vizinhos, mas se sente insegura quanto ao uso das redes sociais e novas formas de comunicação digital.

*Histórias de Usuário - Maria Aparecida*:
1. Como usuária de redes sociais, Maria quer saber como distinguir vídeos deep fake para não ser enganada ao compartilhar conteúdo com seus amigos.
2. Como avó conectada, Maria deseja aprender a verificar a autenticidade de vídeos antes de repassar para seus netos, garantindo que eles recebam apenas informações corretas.
3. Como membro ativo de grupos online, Maria quer participar de conversas com confiança, sabendo que está compartilhando informações verdadeiras e relevantes.

### *Requisitos Funcionais*:
1. O sistema deve disponibilizar vídeos e artigos educativos acessíveis que ensinem a identificar sinais de deep fakes.
2. O sistema deve incluir ferramentas de verificação simples para ajudar os idosos a testar a autenticidade de vídeos e áudios.
3. O sistema deve permitir que os usuários denunciem conteúdo suspeito de ser fake news para revisão.

### *Requisitos Não Funcionais*:
1. O sistema deve ser fácil de usar, com uma interface intuitiva adaptada ao público idoso.
2. O conteúdo educativo deve ser apresentado em linguagem clara e acessível, evitando termos técnicos complicados.
3. O sistema deve garantir segurança e privacidade aos usuários, protegendo suas informações pessoais e dados de navegação.

### *Artefatos Produzidos para Levantamento de Dados*:
1. Entrevistas com idosos para entender suas principais dúvidas e dificuldades ao interagir com conteúdos online.
2. Pesquisa com especialistas em deep fakes para definir os principais sinais de falsificações que serão abordados.
3. Prototipagem de interfaces e testes de usabilidade com o público-alvo para garantir que o sistema atenda às necessidades dos usuários finais.

Essa abordagem centrada no usuário garantirá que a solução seja eficaz e acessível para o público idoso.

Histórias de Usuário Relevantes para o Projeto
Persona 1: João Santos
Eu, como João Santos, quero aprender a identificar deep fakes para evitar compartilhar fake news com meus amigos e familiares.

Eu, como João Santos, preciso de uma ferramenta simples para verificar a autenticidade de vídeos para garantir que as notícias que compartilho sejam verdadeiras.

Eu, como João Santos, quero entender os riscos associados a vídeos deep fakes usados em golpes financeiros para proteger meu patrimônio e evitar fraudes.

Persona 2: Maria Aparecida
Eu, como Maria Aparecida, quero aprender a identificar vídeos e áudios deep fakes para evitar ser enganada por notícias falsas enviadas nos grupos de mensagens.

Eu, como Maria Aparecida, preciso de orientações claras e fáceis de entender para distinguir entre vídeos verdadeiros e falsos nas redes sociais.

Eu, como Maria Aparecida, quero poder compartilhar conteúdos com segurança para não disseminar informações falsas para meus familiares, especialmente meus netos.

Contexto Agrupado por Funcionalidade
Educação sobre Deep Fakes
João Santos: Precisa aprender a identificar deep fakes para não compartilhar notícias falsas.
Maria Aparecida: Quer aprender a identificar deep fakes em vídeos e áudios.
Ferramentas de Verificação
João Santos: Quer uma ferramenta para verificar a autenticidade de vídeos.
Maria Aparecida: Precisa de instruções simples e claras para distinguir vídeos reais dos falsos.
Proteção contra Golpes
João Santos: Deseja entender os riscos financeiros associados a deep fakes.
Maria Aparecida: Quer garantir que o conteúdo que compartilha com a família seja seguro e verdadeiro.
Essas histórias de usuários guiam o desenvolvimento das funcionalidades e ajudam a identificar como a prática extensionista pode minimizar as dores e aumentar a segurança digital dos idosos.
