### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#5]

**Comment by WalisonDaniel** [comment]
Introdução
Este projeto aborda a problemática da disseminação de fake news, com ênfase no uso de deep fakes e seus impactos, especialmente entre o público idoso. Com o avanço das tecnologias de manipulação digital, o uso de deep fakes – vídeos e áudios falsos que parecem reais – tem se tornado um fenômeno crescente, contribuindo para a desinformação em larga escala. O público idoso, que em muitos casos possui menor familiaridade com as tecnologias digitais, se torna particularmente vulnerável a esse tipo de conteúdo. O projeto visa conscientizar esse grupo sobre os perigos das fake news e deep fakes, capacitando-os para identificarem e evitarem a desinformação.

Problema
O problema identificado é a vulnerabilidade do público idoso à desinformação e fake news, especialmente as que envolvem deep fakes. A facilidade com que esses conteúdos manipulados podem ser criados e disseminados leva à confusão e ao engano, contribuindo para a propagação de inverdades. Isso coloca os idosos, que já possuem maior dificuldade em lidar com novas tecnologias, em uma posição de risco.

Objetivos
Objetivo Geral
Desenvolver uma solução educacional que capacite o público idoso a identificar e evitar fake news e deep fakes, promovendo a conscientização sobre as técnicas de desinformação digital.

Objetivos Específicos
Criar materiais informativos acessíveis que expliquem o que são fake news e deep fakes.
Organizar palestras e workshops para ensinar os idosos a reconhecer sinais de manipulação digital.
Desenvolver uma estratégia de comunicação que incentive os idosos a questionar a veracidade das informações recebidas.
Justificativa
A crescente utilização de deep fakes na criação de notícias falsas é uma preocupação global. Esse tipo de tecnologia pode impactar negativamente a percepção da realidade de muitos indivíduos, especialmente os idosos, que tendem a ser menos experientes com as ferramentas digitais. Pesquisas indicam que esse público é mais suscetível a acreditar em informações falsas, o que aumenta a importância de se desenvolver soluções que os protejam contra essa vulnerabilidade. Com o envelhecimento populacional, o problema se torna ainda mais relevante, justificando a necessidade de ações preventivas para mitigar os efeitos nocivos da desinformação.

Público-Alvo
O público-alvo deste projeto são idosos, com idade superior a 60 anos, que possuem acesso à internet, mas apresentam dificuldades em navegar no ambiente digital de forma segura. Eles tendem a consumir informações via redes sociais, aplicativos de mensagens e e-mails, sem a devida checagem da veracidade das informações. Esse grupo também costuma ter menos familiaridade com a identificação de conteúdos manipulados, como vídeos e áudios falsos, o que os torna mais suscetíveis a fake news e deep fakes.
