### ISSUE TITLE
Publico alvo

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#7]

**Comment by ricardotartarini** [comment]
Neste projeto o público alvo são os Idosos, porém, pode ajudar a população em geral, visto que fraudes e golpes envolvendo Deepfakes cresceram cerca de 830% no Brasil nos últimos tempos, nesse caso, idosos são as principais e maiores vítimas desse golpe por conta da dificuldade de não reconhecer oque é e oque não é uma fraude alimentada por inteligência artificial (documentos, áudios, imagens e vídeos) por isso nesse projeto queremos visar e abordar maneiras de se prevenirem e não serem prejudicados pelas Deepfakes.

referência: https://www.terra.com.br/noticias/deepfakes-crescem-830-no-brasil-em-um-ano-aponta-estudo,601f3d28caa943b3728390a82f13cc2b0x3pdhbk.html
