### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by phelipefranco** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-idosos_2#8]

**Comment by phelipefranco** [comment]
Joao Victor vai fazer.

**Comment by WalisonDaniel** [comment]
### *Requisitos Funcionais (RF)*

| *ID*    | *Descrição do Requisito*                                                                 | *Prioridade* |
|-----------|---------------------------------------------------------------------------------------------|----------------|
| RF-001    | O sistema deve fornecer vídeos e artigos educativos sobre deep fakes, com explicações claras e exemplos. | ALTA           |
| RF-002    | O sistema deve incluir uma ferramenta simples para verificar a autenticidade de vídeos deep fake.       | ALTA           |
| RF-003    | O sistema deve permitir que os usuários denunciem vídeos suspeitos de serem deep fakes.                 | MÉDIA          |
| RF-004    | O sistema deve oferecer orientações práticas para reconhecer sinais de manipulação em vídeos e áudios. | ALTA           |
| RF-005    | O sistema deve fornecer um mecanismo de feedback para que os usuários relatem sua experiência ao utilizar as ferramentas. | MÉDIA          |

### *Requisitos Não Funcionais (RNF)*

| *ID*    | *Descrição do Requisito*                                                      | *Prioridade* |
|-----------|---------------------------------------------------------------------------------|----------------|
| RNF-001   | O sistema deve ser intuitivo, com uma interface de fácil uso para idosos.        | ALTA           |
| RNF-002   | O sistema deve ser compatível com dispositivos móveis e navegadores de desktop.  | ALTA           |
| RNF-003   | O tempo de resposta da ferramenta de verificação deve ser inferior a 3 segundos. | MÉDIA          |
| RNF-004   | O conteúdo deve ser apresentado em linguagem acessível, evitando termos técnicos complicados. | ALTA           |
| RNF-005   | O sistema deve garantir a privacidade dos usuários, protegendo seus dados pessoais. | ALTA           |

Esses requisitos garantem que o sistema será acessível, funcional, e atenderá às necessidades do público-alvo, além de garantir uma experiência de uso intuitiva e segura.**

**Comment by WalisonDaniel** [comment]
### *Artefatos para Levantamento de Dados*

Para realizar o levantamento de dados e entrevistas com o público-alvo, o grupo utilizará os seguintes artefatos:

#### *1. Questionários de Percepção sobre Fake News e Deep Fakes*
- *Objetivo*: Avaliar o conhecimento prévio dos idosos sobre fake news e deep fakes, além de identificar as principais dificuldades que eles enfrentam ao usar a internet e redes sociais.
- *Formato*: Questionário de múltipla escolha e perguntas abertas.
- *Estratégia de Aplicação*: 
  - Aplicação *in loco* em centros comunitários e grupos de convivência para idosos.
  - Também será disponibilizado *via web* em grupos de redes sociais voltados para idosos, facilitando o acesso ao questionário.
- *Divulgação*: Será feito através de cartazes nas instituições de convivência de idosos, além de postagens em grupos de WhatsApp e Facebook, com o apoio de membros dessas comunidades.

#### *2. Entrevistas Semiestruturadas*
- *Objetivo*: Coletar informações detalhadas sobre as percepções dos idosos em relação ao conteúdo digital e como eles verificam a autenticidade de informações, além de suas experiências anteriores com fake news.
- *Estratégia de Aplicação*:
  - Realizadas *presencialmente* com participantes que se mostrem dispostos após o preenchimento do questionário.
  - As entrevistas serão gravadas (com consentimento) para análise posterior.

#### *3. Prototipagem de Interface*
- *Objetivo*: Testar a usabilidade da interface proposta para o sistema de verificação de deep fakes.
- *Estratégia de Aplicação*:
  - Realizar sessões de testes com um grupo de idosos, em que eles interajam com protótipos navegáveis da interface.
  - *Feedback* será coletado por meio de observação e formulários, avaliando se as funcionalidades e a interface são intuitivas e fáceis de usar.

Esses artefatos permitirão uma análise aprofundada das necessidades do público-alvo, guiando o desenvolvimento da solução para que ela seja eficaz e acessível.

**Comment by WalisonDaniel** [comment]
### *Referências*

1. *LOPEZ, M.* Deepfakes: Understanding the Impact on Misinformation and Privacy. Journal of Information Security, 2022.
2. *WANG, T., & GU, J.* Detecting Deepfake Media: A Survey. IEEE Transactions on Multimedia, 2021. 
3. *BBC News. *What are Deepfakes and How Can You Spot Them? Disponível em: [https://www.bbc.com/news/technology-50291077](https://www.bbc.com/news/technology-50291077). Acesso em: 01 set. 2024.
4. *SOUSA, P. R., & SILVA, M. B. *Fake News e a Terceira Idade: Desafios na Era Digital. Revista de Comunicação e Sociedade, 2023.
5. *LUCA, D., & MARTINS, L.* Como a Tecnologia de Deepfakes Está Impactando a Sociedade: Uma Análise de Casos Recentes. Revista Brasileira de Ciências da Informação, 2023.
6. *The Guardian. *Deepfakes: How Are They Made and How to Spot Them? Disponível em: [https://www.theguardian.com/technology/deepfakes](https://www.theguardian.com/technology/deepfakes). Acesso em: 30 ago. 2024.
7. *VIEIRA, A. S., & COSTA, P. R. *Educação Digital para Idosos: O Papel da Tecnologia no Combate às Fake News. Proceedings of the Digital Inclusion Conference, 2022.

**Comment by WalisonDaniel** [comment]
Objetivo Geral: O objetivo deste projeto é alertar e informar os idosos sobre os perigos das fake news envolvendo deep fakes, uma tecnologia que pode criar vídeos e áudios falsificados que parecem extremamente reais. O foco é aumentar a conscientização sobre essa ameaça, oferecendo ferramentas práticas para reconhecer e evitar a disseminação dessas falsificações digitais.

Objetivos Específicos:

Explicar o conceito de deep fake e seu funcionamento: Fornecer uma explicação simples e acessível sobre o que é um deep fake, como ele é criado e como essa tecnologia pode ser usada para espalhar desinformação e enganar o público.

Ensinar técnicas para identificar deep fakes: Capacitar os idosos com métodos para reconhecer sinais de vídeos ou áudios manipulados, como inconsistências visuais ou sonoras, além de sugerir ferramentas digitais de verificação de autenticidade de conteúdos online.

Esses objetivos ajudarão a estruturar a apresentação de forma educativa e prática para o público.
